apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: j3j688u3g-nodejs 
  janus-idp.io/tekton: j3j688u3g-nodejs
  backstage.io/kubernetes-id: j3j688u3g-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: j3j688u3g-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml