apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: j3j688u3g-nodejs-gitops
  description: This is GitOps manifest for j3j688u3g-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=j3j688u3g-nodejs
    backstage.io/kubernetes-id: j3j688u3g-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: j3j688u3g-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:j3j688u3g-nodejs
